import { useEffect, useState } from "react";
import type { Automation, AutomationAction, AutomationCondition, AutomationCreate, Project, User } from "@taskforge/contracts";
import { Check, Plus, Save, Trash2, Zap } from "lucide-react";
import { api } from "../lib/api";

const fields = [{ value: "status", label: "Status" }, { value: "priority", label: "Priority" }, { value: "assigneeId", label: "Assignee" }, { value: "pullRequestState", label: "PR state" }, { value: "phaseId", label: "Phase" }, { value: "branch", label: "Branch" }, { value: "estimatePoints", label: "Estimate" }] as const;
const operators = ["equals", "not_equals", "changed_to", "is_empty", "is_not_empty"] as const;
const services = ["agent-api", "github-actions", "taskforge"];
const blankCondition = (): AutomationCondition => ({ field: "status", operator: "equals", value: "" });
const blankAction = (): AutomationAction => ({ field: "status", valueType: "static", value: "IN_PROGRESS" });

export function AutomationManager({ project, users }: { project: Project | null; users: User[] }) {
  const [rules, setRules] = useState<Automation[]>([]);
  const [editing, setEditing] = useState<string | null>(null);
  const [name, setName] = useState(""); const [enabled, setEnabled] = useState(true); const [trigger, setTrigger] = useState<AutomationCreate["trigger"]>("TASK_UPDATED"); const [actorType, setActorType] = useState<AutomationCreate["actorType"]>("ANY"); const [actorId, setActorId] = useState<string | null>(null); const [service, setService] = useState<string | null>(null);
  const [conditions, setConditions] = useState<AutomationCondition[]>([blankCondition()]); const [actions, setActions] = useState<AutomationAction[]>([blankAction()]); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { if (project) api.automations(project.id).then(({ automations }) => setRules(automations)).catch(() => setRules([])); }, [project]);
  function reset() { setEditing(null); setName(""); setEnabled(true); setTrigger("TASK_UPDATED"); setActorType("ANY"); setActorId(null); setService(null); setConditions([blankCondition()]); setActions([blankAction()]); }
  function edit(rule: Automation) { setEditing(rule.id); setName(rule.name); setEnabled(rule.enabled); setTrigger(rule.trigger); setActorType(rule.actorType); setActorId(rule.actorId); setService(rule.service); setConditions(rule.conditions); setActions(rule.actions); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function save() { if (!project) return; setError(""); try { const input = { name, enabled, trigger, actorType, actorId, service, conditions, actions } as AutomationCreate; const result = editing ? await api.updateAutomation(editing, input) : await api.createAutomation(project.id, input); setRules((items) => editing ? items.map((item) => item.id === result.automation.id ? result.automation : item) : [result.automation, ...items]); reset(); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } catch (err) { setError(err instanceof Error ? err.message : "Could not save automation"); } }
  async function remove(id: string) { if (!window.confirm("Delete this automation?")) return; await api.deleteAutomation(id); setRules((items) => items.filter((item) => item.id !== id)); if (editing === id) reset(); }
  const updateCondition = (index: number, patch: Partial<AutomationCondition>) => setConditions((items) => items.map((item, i) => i === index ? { ...item, ...patch } : item));
  const updateAction = (index: number, patch: Partial<AutomationAction>) => setActions((items) => items.map((item, i) => i === index ? { ...item, ...patch } : item));
  if (!project) return null;
  return <div className="automation-page">
    <header className="automation-page-header"><div className="automation-heading"><span className="automation-icon"><Zap /></span><div><span className="eyebrow">Project workflow</span><h2>Automations</h2><p>Keep {project.name} moving with rules that react to task changes.</p></div></div><div className="automation-header-meta"><strong>{rules.filter((rule) => rule.enabled).length}</strong><span>active rules</span></div></header>
    {error && <div className="automation-alert error">{error}</div>}{saved && <div className="automation-alert success"><Check /> Automation saved</div>}
    <div className="automation-layout"><section className="automation-card automation-builder"><div className="automation-card-heading"><div><span className="eyebrow">Rule builder</span><h3>{editing ? "Edit automation" : "Create an automation"}</h3></div><span className="step-badge">{editing ? "Editing" : "New rule"}</span></div><label>Rule name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Assign task to actioner" /></label><div className="automation-two-col"><label>When<select value={trigger} onChange={(e) => setTrigger(e.target.value as AutomationCreate["trigger"])}><option value="TASK_UPDATED">A task is updated</option><option value="TASK_CREATED">A task is created</option></select></label><label>Triggered by<select value={actorType} onChange={(e) => setActorType(e.target.value as AutomationCreate["actorType"])}><option value="ANY">Anyone</option><option value="USER">A specific user</option><option value="SERVICE">A service</option></select></label></div>{actorType === "USER" && <label>Specific user<select value={actorId ?? ""} onChange={(e) => setActorId(e.target.value)}><option value="">Choose a user</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}{actorType === "SERVICE" && <label>Service<select value={service ?? ""} onChange={(e) => setService(e.target.value)}><option value="">Choose a service</option>{services.map((s) => <option key={s}>{s}</option>)}</select></label>}
      <div className="automation-section-title"><span>Conditions</span><small>All conditions must match</small></div>{conditions.map((condition, index) => <div className="automation-rule-row" key={index}><select value={condition.field} onChange={(e) => updateCondition(index, { field: e.target.value as AutomationCondition["field"] })}>{fields.map((field) => <option key={field.value} value={field.value}>{field.label}</option>)}</select><select value={condition.operator} onChange={(e) => updateCondition(index, { operator: e.target.value as AutomationCondition["operator"] })}>{operators.map((operator) => <option key={operator} value={operator}>{operator.replaceAll("_", " ")}</option>)}</select>{!condition.operator.includes("empty") && <input value={condition.value ?? ""} placeholder="Value" onChange={(e) => updateCondition(index, { value: e.target.value })} />}<button className="automation-remove" onClick={() => setConditions((items) => items.filter((_, i) => i !== index))} aria-label="Remove condition"><Trash2 /></button></div>)}<button className="automation-add" onClick={() => setConditions((items) => [...items, blankCondition()])}><Plus /> Add condition</button>
      <div className="automation-section-title"><span>Actions</span><small>Apply these changes</small></div>{actions.map((action, index) => <div className="automation-rule-row" key={index}><select value={action.field} onChange={(e) => updateAction(index, { field: e.target.value as AutomationAction["field"] })}>{fields.map((field) => <option key={field.value} value={field.value}>{field.label}</option>)}</select><select value={action.valueType} onChange={(e) => { const valueType = e.target.value as AutomationAction["valueType"]; updateAction(index, { valueType, value: valueType === "actor" || valueType === "null" ? null : action.value }); }}>{[<option key="static" value="static">Set a value</option>, <option key="actor" value="actor">Triggering user</option>, <option key="user" value="user">Specific user ID</option>, <option key="service" value="service">Service value</option>, <option key="null" value="null">Clear the field</option>]}</select>{(action.valueType === "static" || action.valueType === "user" || action.valueType === "service") && <input value={action.value ?? ""} placeholder="Value" onChange={(e) => updateAction(index, { value: e.target.value })} />}<button className="automation-remove" onClick={() => setActions((items) => items.filter((_, i) => i !== index))} aria-label="Remove action"><Trash2 /></button></div>)}<button className="automation-add" onClick={() => setActions((items) => [...items, blankAction()])}><Plus /> Add action</button>
      <div className="automation-builder-footer"><label className="automation-enabled"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} /> Enabled</label><span /><button className="button button-primary" disabled={!name.trim() || !actions.length} onClick={() => void save()}><Save /> {editing ? "Update rule" : "Create rule"}</button>{editing && <button className="button button-secondary" onClick={reset}>Cancel</button>}</div>
    </section><aside className="automation-card automation-list-card"><div className="automation-card-heading"><div><span className="eyebrow">Configured rules</span><h3>{rules.length ? `${rules.length} automation${rules.length === 1 ? "" : "s"}` : "No automations yet"}</h3></div></div>{rules.length ? <div className="automation-list">{rules.map((rule) => <article className="automation-list-item" key={rule.id}><span className={`automation-status${rule.enabled ? " on" : ""}`} /><div><strong>{rule.name}</strong><small>{rule.enabled ? "Active" : "Paused"} · {rule.trigger === "TASK_CREATED" ? "On task creation" : "On task update"}</small></div><button className="automation-edit" onClick={() => edit(rule)}>Edit</button><button className="automation-remove" onClick={() => void remove(rule.id)} aria-label={`Delete ${rule.name}`}><Trash2 /></button></article>)}</div> : <div className="automation-empty"><Zap /><strong>Automate the routine work</strong><span>Start with a condition and an action. Rules run whenever a task changes.</span></div>}</aside></div>
  </div>;
}
