import { useState } from "react";

export function PhaseMergeModal({ phaseNumber, sourceBranch, targetBranch, title, body, compareUrl, onAuthorize, onClose }: {
  phaseNumber: number; sourceBranch: string; targetBranch: string; title: string; body: string; compareUrl: string;
  onAuthorize: () => Promise<void>; onClose: () => void;
}) {
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState("");
  async function copy(label: string, value: string) {
    try { await navigator.clipboard.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1600); } catch { setCopied(""); }
  }
  async function authorize() { setBusy(true); try { await onAuthorize(); if (compareUrl) window.open(compareUrl, "_blank", "noopener,noreferrer"); } finally { setBusy(false); } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="phase-merge-modal" role="dialog" aria-modal="true" aria-labelledby="phase-merge-title"><header><div><span className="modal-kicker">Phase {phaseNumber}</span><h2 id="phase-merge-title">Prepare phase merge</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><span aria-hidden="true">×</span></button></header><div className="phase-merge-modal-body"><p>Review the prepared pull request details, copy them into GitHub, then authorize and open the compare page.</p><dl><div><dt>Source branch</dt><dd><code>{sourceBranch}</code><button type="button" className="button button-secondary" onClick={() => copy("source", sourceBranch)}>{copied === "source" ? "Copied" : "Copy"}</button></dd></div><div><dt>Target branch</dt><dd><code>{targetBranch}</code><button type="button" className="button button-secondary" onClick={() => copy("target", targetBranch)}>{copied === "target" ? "Copied" : "Copy"}</button></dd></div></dl><label>PR title<div className="phase-merge-copy-row"><input value={title} readOnly /><button type="button" className="button button-secondary" onClick={() => copy("title", title)}>{copied === "title" ? "Copied" : "Copy"}</button></div></label><label>PR description<textarea value={body} readOnly rows={8} /><button type="button" className="button button-secondary phase-merge-copy-button" onClick={() => copy("body", body)}>{copied === "body" ? "Copied" : "Copy description"}</button></label>{compareUrl && <label>GitHub compare link<div className="phase-merge-copy-row"><input value={compareUrl} readOnly /><button type="button" className="button button-secondary" onClick={() => copy("link", compareUrl)}>{copied === "link" ? "Copied" : "Copy"}</button></div></label>}</div><footer><button type="button" className="button button-secondary" onClick={onClose} disabled={busy}>Cancel</button><button type="button" className="button button-primary" disabled={busy} onClick={authorize}>{busy ? "Preparing…" : "Authorize & open GitHub"}</button></footer></section></div>;
}
