import type { FormEvent } from "react";
import type { ApiTokenMetadata, User } from "@taskforge/contracts";
import type { AgentDetailTab } from "../../../../lib/settingsNav";

export type AgentsSectionProps = {
  isAdmin: boolean;
  agents: User[];
  selectedAgentId: string;
  selectedAgent: User | undefined;
  agentDetailTab: AgentDetailTab;
  showNewAgentForm: boolean;
  agentName: string;
  agentEmail: string;
  creatingAgent: boolean;
  tokens: ApiTokenMetadata[];
  tokensLoading: boolean;
  tokensError: string;
  tokenName: string;
  expiresInDays: string;
  issuingToken: boolean;
  issuedToken: string;
  revealedTokenId: string;
  copied: boolean;
  avatarUploading: boolean;
  onToggleNewAgentForm: () => void;
  onOpenNewAgentForm: () => void;
  onCloseNewAgentForm: () => void;
  onAgentNameChange: (value: string) => void;
  onAgentEmailChange: (value: string) => void;
  onAddAgent: (event: FormEvent) => void | Promise<void>;
  onSelectAgent: (id: string) => void;
  onAgentDetailTabChange: (tab: AgentDetailTab) => void;
  onAgentUpdated: (user: User) => void;
  onSuccess: (text: string) => void;
  onError: (text: string) => void;
  onIssueToken: (event: FormEvent) => void | Promise<void>;
  onTokenNameChange: (value: string) => void;
  onExpiresInDaysChange: (value: string) => void;
  onRequestRevealToken: (token: ApiTokenMetadata) => void;
  onRevokeToken: (id: string) => void | Promise<void>;
  onCopyToken: () => void | Promise<void>;
  onUpdateAgentAvatar: (file: File) => void | Promise<void>;
  onRemoveAgentAvatar: () => void | Promise<void>;
  onDeleteAgent: () => void | Promise<void>;
};
