import { randomUUID } from "node:crypto";
import type { AgentBudget, AgentBudgetLimits, AgentBudgetScope, AgentUsageEventInput, AgentUsageReport, AgentUsageTotals } from "@taskforge/contracts";
import { ForbiddenError, NotFoundError, ValidationError } from "./errors.js";
import type { RequestContext } from "./context.js";
import type { AgentBudgetEntity, TaskEntity } from "./models.js";
import type { RepositorySet, UnitOfWork } from "./repositories.js";

const limitKeys = ["totalTokens", "costMicros", "toolCalls", "runtimeMs", "retries", "forcedCycles"] as const;
export function exceededLimits(totals: AgentUsageTotals, limits: AgentBudgetLimits) { return limitKeys.filter((key) => limits[key] !== undefined && totals[key] >= limits[key]!); }
async function budgetTotals(repositories: RepositorySet, budget: AgentBudgetEntity, task: TaskEntity) { if (budget.scope === "PROJECT") return repositories.agentUsage.totals({ projectId: task.projectId }); if (budget.scope === "PHASE") return repositories.agentUsage.totals({ phaseId: budget.scopeId }); return repositories.agentUsage.totals({ taskId: budget.scopeId }); }
export async function assertAgentBudgetAllows(repositories: RepositorySet, task: TaskEntity) { if (!repositories.agentBudgets || !repositories.agentUsage) return; for (const budget of await repositories.agentBudgets.listApplicable(task.projectId, task.phaseId, task.id)) { if (budget.action === "WARN") continue; const exceeded = exceededLimits(await budgetTotals(repositories, budget, task), budget.limits); if (exceeded.length) throw new ValidationError(`Agent ${budget.scope.toLowerCase()} budget is ${budget.action === "PAUSE" ? "paused" : "exhausted"} (${exceeded.join(", ")}); an operator must adjust the budget before starting more work`); } }

export class AgentUsageApplicationService {
  constructor(private readonly unitOfWork: UnitOfWork, private readonly now = () => new Date().toISOString(), private readonly newId = randomUUID) {}
  async record(context: RequestContext, runId: string, input: AgentUsageEventInput) { return this.unitOfWork.run(async (repositories) => { const run = await repositories.runs.findById(runId); if (!run) throw new NotFoundError("Agent run"); const task = await repositories.tasks.findById(run.taskId); if (!task) throw new NotFoundError("Task"); await this.authorize(repositories, context, run.projectId); if (context.actor.kind !== "AGENT" || run.leaseOwner !== context.actor.userId || run.status !== "RUNNING" || run.controlState !== "ACTIVE") throw new ForbiddenError("Only the current active run lease owner can report usage"); const cycle = await repositories.runs.cycleState(run.taskId); const result = await repositories.agentUsage.append({ id: this.newId(), runId, taskId: run.taskId, phaseId: task.phaseId, projectId: run.projectId, ...input, retry: run.attemptCount > 1, forcedCycle: cycle.limit > 6 && cycle.count > 6, createdAt: this.now() }); if (!result.created) return { ...result, budgetDecisions: [] }; const budgetDecisions: Array<{ budgetId: string; action: AgentBudget["action"]; exceeded: string[] }> = []; for (const budget of await repositories.agentBudgets.listApplicable(task.projectId, task.phaseId, task.id)) { const exceeded = exceededLimits(await budgetTotals(repositories, budget, task), budget.limits); if (!exceeded.length) continue; if (budget.action === "PAUSE") { const paused = await repositories.runs.applyIntervention(run.id, run.controlVersion, { controlState: "PAUSED", lastError: "Paused because an agent usage budget was reached" }, this.now()); if (!paused) continue; await repositories.tokens.revokeRunCredential(run.id, this.now()); } budgetDecisions.push({ budgetId: budget.id, action: budget.action, exceeded }); await repositories.activity.record({ projectId: run.projectId, taskId: run.taskId, actorId: context.actor.userId, action: `agent_usage.budget_${budget.action.toLowerCase()}`, metadata: { runId, budgetId: budget.id, scope: budget.scope, exceeded } }); } return { ...result, budgetDecisions }; }); }
  async runReport(context: RequestContext, runId: string): Promise<AgentUsageReport> { return this.unitOfWork.run(async (repositories) => { const run = await repositories.runs.findById(runId); if (!run) throw new NotFoundError("Agent run"); await this.authorize(repositories, context, run.projectId); return repositories.agentUsage.report({ runId }); }); }
  async projectReport(context: RequestContext, projectId: string, filters: { phaseId?: string; taskId?: string; provider?: string; model?: string }): Promise<AgentUsageReport> { return this.unitOfWork.run(async (repositories) => { await this.authorize(repositories, context, projectId); if (filters.taskId) { const task = await repositories.tasks.findById(filters.taskId); if (!task || task.projectId !== projectId) throw new ValidationError("Task does not belong to this project"); } if (filters.phaseId) { const phase = await repositories.phases.findById(filters.phaseId); if (!phase || phase.projectId !== projectId) throw new ValidationError("Phase does not belong to this project"); } return repositories.agentUsage.report({ projectId, ...filters }); }); }
  async listBudgets(context: RequestContext, projectId: string) { return this.unitOfWork.run(async (repositories) => { await this.authorize(repositories, context, projectId); return repositories.agentBudgets.list(projectId); }); }
  async saveBudget(context: RequestContext, projectId: string, scope: AgentBudgetScope, scopeId: string, input: Pick<AgentBudget, "action" | "limits">) { return this.unitOfWork.run(async (repositories) => { const project = await this.authorize(repositories, context, projectId); if (context.actor.kind !== "HUMAN" || (context.actor.role !== "ADMIN" && context.actor.userId !== project.ownerId)) throw new ForbiddenError("Only a project owner or administrator can configure agent budgets"); if (scope === "PROJECT" && scopeId !== projectId) throw new ValidationError("Project budget scopeId must match the project"); if (scope === "PHASE") { const phase = await repositories.phases.findById(scopeId); if (!phase || phase.projectId !== projectId) throw new ValidationError("Phase does not belong to this project"); } if (scope === "TASK") { const task = await repositories.tasks.findById(scopeId); if (!task || task.projectId !== projectId) throw new ValidationError("Task does not belong to this project"); } const existing = (await repositories.agentBudgets.list(projectId)).find((item) => item.scope === scope && item.scopeId === scopeId); const now = this.now(); const budget: AgentBudgetEntity = { id: existing?.id ?? this.newId(), projectId, scope, scopeId, action: input.action, limits: input.limits, createdAt: existing?.createdAt ?? now, updatedAt: now }; await repositories.agentBudgets.save(budget); await repositories.activity.record({ projectId, actorId: context.actor.userId, action: "agent_usage.budget_configured", metadata: { budgetId: budget.id, scope, scopeId, action: input.action, limits: input.limits } }); return budget; }); }
  async deleteBudget(context: RequestContext, projectId: string, scope: AgentBudgetScope, scopeId: string) { return this.unitOfWork.run(async (repositories) => { const project = await this.authorize(repositories, context, projectId); if (context.actor.kind !== "HUMAN" || (context.actor.role !== "ADMIN" && context.actor.userId !== project.ownerId)) throw new ForbiddenError("Only a project owner or administrator can configure agent budgets"); return repositories.agentBudgets.delete(projectId, scope, scopeId); }); }
  private async authorize(repositories: RepositorySet, context: RequestContext, projectId: string) { const project = await repositories.projects.findById(projectId); if (!project) throw new NotFoundError("Project"); if (context.actor.role !== "ADMIN" && !(await repositories.memberships.isMember(projectId, context.actor.userId))) throw new ForbiddenError("You are not a member of this project"); return project; }
}
