import { randomUUID } from "node:crypto";
import { Buffer } from "node:buffer";
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from "./errors.js";
import type { ProjectContext, RequestContext } from "./context.js";
import type { PhaseEntity, ProjectEntity, UserEntity } from "./models.js";
import type { RepositorySet, UnitOfWork } from "./repositories.js";
import type { PhaseService, ProjectCreateInput, ProjectService, UserService } from "./services.js";

async function projectAccess(repositories: RepositorySet, context: RequestContext, projectId: string) {
  const project = await repositories.projects.findById(projectId);
  if (!project) throw new NotFoundError("Project");
  if (context.actor.role !== "ADMIN" && !(await repositories.memberships.isMember(projectId, context.actor.userId))) throw new ForbiddenError("You are not a member of this project");
  return project;
}

export class ProjectApplicationService implements ProjectService {
  constructor(private readonly unitOfWork: UnitOfWork, private readonly now: () => string = () => new Date().toISOString(), private readonly newId: () => string = randomUUID) {}
  async list(context: RequestContext) { return this.unitOfWork.run((repositories) => repositories.projects.listAccessible(context.actor.userId, context.actor.role === "ADMIN")); }
  async get(context: ProjectContext) { return this.unitOfWork.run(async (repositories) => { const project = await projectAccess(repositories, context, context.projectId); const members = await repositories.memberships.list(context.projectId); return { ...project, members: members.map((member) => ({ ...member, projectRole: member.id === project.ownerId ? "OWNER" as const : "MEMBER" as const })) }; }); }
  async create(context: RequestContext, input: ProjectCreateInput) { return this.unitOfWork.run(async (repositories) => { const now = this.now(); const project: ProjectEntity = { ...input, id: this.newId(), ownerId: context.actor.userId, createdAt: now, updatedAt: now }; await repositories.projects.create(project); await repositories.memberships.add(project.id, context.actor.userId, "OWNER"); await repositories.phases.create({ id: this.newId(), projectId: project.id, number: 1, goal: "Plan and deliver the first project milestone.", isActive: true, createdAt: now, updatedAt: now }); return project; }); }
  async update(context: ProjectContext, input: Partial<Pick<ProjectEntity, "name" | "description" | "repoUrl" | "color">>) { return this.unitOfWork.run(async (repositories) => { await projectAccess(repositories, context, context.projectId); return repositories.projects.update(context.projectId, input); }); }
  async delete(context: ProjectContext) { return this.unitOfWork.run(async (repositories) => { const project = await projectAccess(repositories, context, context.projectId); if (context.actor.role !== "ADMIN" && project.ownerId !== context.actor.userId) throw new ForbiddenError("Only the project owner or an administrator can delete this project"); await repositories.projects.delete(context.projectId); }); }
  async addMember(context: ProjectContext, userId: string, role: "OWNER" | "MEMBER") { return this.unitOfWork.run(async (repositories) => { const project = await projectAccess(repositories, context, context.projectId); if (context.actor.role !== "ADMIN" && project.ownerId !== context.actor.userId) throw new ForbiddenError("Only the project owner or an administrator can manage members"); const user = await repositories.users.findById(userId); if (!user) throw new NotFoundError("User"); if (role === "OWNER" && userId !== project.ownerId) throw new ValidationError("A project can only have its original owner"); await repositories.memberships.add(context.projectId, userId, userId === project.ownerId ? "OWNER" : role); }); }
  async removeMember(context: ProjectContext, userId: string) { return this.unitOfWork.run(async (repositories) => { const project = await projectAccess(repositories, context, context.projectId); if (context.actor.role !== "ADMIN" && project.ownerId !== context.actor.userId) throw new ForbiddenError("Only the project owner or an administrator can manage members"); if (userId === project.ownerId) throw new ValidationError("The project owner cannot be removed"); if (!(await repositories.memberships.isMember(context.projectId, userId))) throw new NotFoundError("Project member"); await repositories.tasks.unassignForProjectMember(context.projectId, userId); await repositories.memberships.remove(context.projectId, userId); }); }
}

export class PhaseApplicationService implements PhaseService {
  constructor(private readonly unitOfWork: UnitOfWork, private readonly now: () => string = () => new Date().toISOString(), private readonly newId: () => string = randomUUID) {}
  async list(context: ProjectContext) { await this.unitOfWork.run((repositories) => projectAccess(repositories, context, context.projectId)); return this.unitOfWork.run((repositories) => repositories.phases.list(context.projectId)); }
  async create(context: ProjectContext, input: { number: number; goal: string; isActive: boolean }) { return this.unitOfWork.run(async (repositories) => { await projectAccess(repositories, context, context.projectId); if (input.isActive) await repositories.phases.deactivateOthers(context.projectId); const now = this.now(); const phase: PhaseEntity = { ...input, id: this.newId(), projectId: context.projectId, createdAt: now, updatedAt: now }; return repositories.phases.create(phase); }); }
  async update(context: RequestContext, phaseId: string, input: Partial<Pick<PhaseEntity, "number" | "goal" | "isActive">>) { return this.unitOfWork.run(async (repositories) => { const existing = await repositories.phases.findById(phaseId); if (!existing) throw new NotFoundError("Phase"); await projectAccess(repositories, context, existing.projectId); if (input.isActive) await repositories.phases.deactivateOthers(existing.projectId, phaseId); return repositories.phases.update(phaseId, input); }); }
  async delete(context: RequestContext, phaseId: string) { return this.unitOfWork.run(async (repositories) => { const existing = await repositories.phases.findById(phaseId); if (!existing) throw new NotFoundError("Phase"); await projectAccess(repositories, context, existing.projectId); await repositories.phases.delete(phaseId); }); }
}

export class UserApplicationService implements UserService {
  constructor(private readonly unitOfWork: UnitOfWork, private readonly now: () => string = () => new Date().toISOString(), private readonly newId: () => string = randomUUID, private readonly tokenAdapter: { create: () => { token: string; prefix: string }; hash: (token: string) => string } = { create: () => { throw new Error("Token issuer is not configured"); }, hash: () => { throw new Error("Token issuer is not configured"); } }) {}
  async list(context: RequestContext) { if (context.actor.role !== "ADMIN") throw new ForbiddenError("Administrator access required"); return this.unitOfWork.run((repositories) => repositories.users.list()); }
  async updateProfile(context: RequestContext, input: { name: string; email: string }) { if (context.actor.kind !== "HUMAN") throw new ValidationError("Agent profiles are managed by administrators"); return this.unitOfWork.run((repositories) => repositories.users.saveProfile(context.actor.userId, input)); }
  async updateAvatar(context: RequestContext, userId: string, avatarUrl: string | null) { if (context.actor.userId !== userId && context.actor.role !== "ADMIN") throw new ForbiddenError("Administrator access required"); if (avatarUrl !== null) { const match = avatarUrl.match(/^data:(image\/(?:png|jpeg|jpg|gif|webp));base64,([A-Za-z0-9+/=]+)$/i); if (!match || Buffer.byteLength(match[2]!, "base64") > 2 * 1024 * 1024) throw new ValidationError("Profile pictures must be valid images smaller than 2 MB"); } return this.unitOfWork.run(async (repositories) => { if (!(await repositories.users.findById(userId))) throw new NotFoundError("User"); return repositories.users.updateAvatar(userId, avatarUrl); }); }
  async createAgent(context: RequestContext, input: { name: string; email?: string }) { if (context.actor.role !== "ADMIN") throw new ForbiddenError("Administrator access required"); const id = this.newId(); return this.unitOfWork.run((repositories) => repositories.users.createAgent({ id, name: input.name, email: input.email ?? `${id.slice(0, 8)}@agents.taskforge.local`, createdAt: this.now() })); }
  async deleteAgent(context: RequestContext, agentId: string) { if (context.actor.role !== "ADMIN") throw new ForbiddenError("Administrator access required"); return this.unitOfWork.run(async (repositories) => { const agent = await repositories.users.findById(agentId); if (!agent) throw new NotFoundError("Agent"); if (agent.kind !== "AGENT") throw new ValidationError("Only agent identities can be deleted"); if (await repositories.users.hasAgentHistory(agentId)) throw new ConflictError("This agent has project or task history and cannot be deleted. Revoke its tokens and remove its project memberships instead."); await repositories.users.deleteAgent(agentId); }); }
  private canManage(context: RequestContext, userId: string) { if (context.actor.userId !== userId && context.actor.role !== "ADMIN") throw new ForbiddenError("Administrator access required"); }
  async listTokens(context: RequestContext, userId: string) { this.canManage(context, userId); return this.unitOfWork.run(async (repositories) => { if (!(await repositories.users.findById(userId))) throw new NotFoundError("User"); return repositories.tokens.listForUser(userId); }); }
  async issueToken(context: RequestContext, userId: string, input: { name: string; expiresInDays: number | null }) { this.canManage(context, userId); return this.unitOfWork.run(async (repositories) => { if (!(await repositories.users.findById(userId))) throw new NotFoundError("User"); const { token, prefix } = this.tokenAdapter.create(); const now = new Date(this.now()); const expiresAt = input.expiresInDays === null ? null : new Date(now.getTime() + input.expiresInDays * 86_400_000).toISOString(); await repositories.tokens.create({ id: this.newId(), userId, name: input.name, prefix, hash: this.tokenAdapter.hash(token), expiresAt, createdAt: now.toISOString() }); return { token, prefix, expiresAt }; }); }
  async revokeToken(context: RequestContext, tokenId: string) { return this.unitOfWork.run(async (repositories) => { const token = await repositories.tokens.findById(tokenId); if (!token) throw new NotFoundError("Token"); this.canManage(context, token.userId); await repositories.tokens.revoke(tokenId); }); }
}
